### ISSUE TITLE
Salesfloor Tag not Delivering Email Values

### ISSUE THREAD

**Issue by daviddoss** [saksdirect/saks-signal#1]
This is the tag:
https://hub.signal.co/sites/KsHEgHS/tags/4923836/attributes

This is the data binding expression:
https://hub.signal.co/sites/KsHEgHS/data/1080045/inputs

Expected value: 
'customer_email': '[[emailAddress]]'

Actual result: nothing for that key-value pair (see screenshots).

[SalesFlood_Request_URLs.txt](https://github.com/saksdirect/saks-signal/files/1046172/SalesFlood_Request_URLs.txt)
![2017-06-01 6 10 25 pm](https://cloud.githubusercontent.com/assets/8964880/26703055/d2fbbc9a-46f5-11e7-90cf-53528698695d.png)
![2017-06-01 6 10 10 pm](https://cloud.githubusercontent.com/assets/8964880/26703056/d2ffc45c-46f5-11e7-922a-6c89e1df1771.png)

**Comment by fiftyfactorauthentication** [comment]
Come on man, this isn't your first rodeo. Where's the url to reproduce?

**Comment by daviddoss** [comment]
To reproduce, place an order on qa.saks.com. On the order confirmation page, search for "salesfloor" within the Network tab of Chrome Dev tools.

Expected value is an email address: me@example.com

**Comment by fiftyfactorauthentication** [comment]
Checkout process will have to be debugged by the team responsible for checkout. There's an  error in your screenshots that has been reported to the front end devs at Saks multiple times. You've also got a signal error in the console directly above that. Resolve those and circle back if it's a confirmed issue with this repo.
